from settings import MINDSDB_EMAIL, MINDSDB_PASSWORD, SECRET_KEY, MDB_URI

class Config:
    MINDSDB_EMAIL = MINDSDB_EMAIL
    MINDSDB_PASSWORD = MINDSDB_PASSWORD
    SECRET_KEY = SECRET_KEY
    MDB_URI = MDB_URI
